# Generated by Django 5.2.17 on 2026-08-16 15:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_node_id', models.BigIntegerField(unique=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='CrossingNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crossing_type', models.CharField(blank=True, max_length=24)),
                ('kerb', models.CharField(blank=True, max_length=20)),
                ('junction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geodata.junction')),
            ],
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.CharField(max_length=32, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('length_m', models.FloatField()),
                ('highway_class', models.CharField(max_length=24)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('oneway', models.BooleanField(default=False)),
                ('lanes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('surface', models.CharField(blank=True, max_length=40)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('from_junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='geodata.junction')),
                ('to_junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='geodata.junction')),
            ],
        ),
        migrations.CreateModel(
            name='FootpathLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5)),
                ('source', models.CharField(choices=[('mapped', 'mapped'), ('tagged', 'tagged'), ('assumed', 'assumed')], max_length=8)),
                ('width_m', models.FloatField(blank=True, null=True)),
                ('surface', models.CharField(blank=True, max_length=40)),
                ('wheelchair', models.CharField(blank=True, max_length=20)),
                ('kerb', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(default=0.5)),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footpaths', to='geodata.roadsegment')),
            ],
            options={
                'unique_together': {('road_segment', 'side')},
            },
        ),
    ]
