# Generated by Django 5.2.17 on 2026-08-16 15:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('osm_type', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=48)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tags', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('osm_type', 'osm_id')},
            },
        ),
    ]
