# Generated by Django 5.2.17 on 2026-08-16 16:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geodata', '0002_poi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='reports/%Y/%m/')),
                ('category', models.CharField(choices=[('blocked_hawker', 'Blocked by hawkers'), ('blocked_parked_vehicle', 'Blocked by parked vehicles'), ('broken_surface', 'Broken surface'), ('open_drain', 'Open drain'), ('no_kerb_ramp', 'No kerb ramp'), ('dead_end', 'Footpath dead-ends'), ('construction', 'Construction'), ('waterlogging', 'Waterlogging'), ('encroachment', 'Encroachment'), ('obstacle_pole', 'Pole/obstacle'), ('narrow', 'Too narrow'), ('good', 'Actually good!')], max_length=32)),
                ('severity', models.PositiveSmallIntegerField(default=2)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('stable_key', models.CharField(blank=True, max_length=32)),
                ('side', models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right'), ('road', 'road')], max_length=5)),
                ('position_fraction', models.FloatField(blank=True, null=True)),
                ('near_poi_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=8)),
                ('submitter_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('road_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.roadsegment')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=5)),
                ('scores', models.JSONField(default=dict)),
                ('hazard_points', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.roadsegment')),
            ],
            options={
                'unique_together': {('road_segment', 'side')},
            },
        ),
    ]
